name: arisan_digital
description: Arisan Digital.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.0.2
  percent_indicator: ^4.2.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_dotenv: ^5.0.2
  google_sign_in: ^5.4.1
  loading_animation_widget: ^1.2.0+3
  overlay_loading_progress: ^1.0.0
  upgrader: ^4.6.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  shimmer: ^2.0.0
  awesome_snackbar_content: ^0.0.8
  pattern_formatter: ^2.0.0
  intl: ^0.17.0
  scrollable_positioned_list: ^0.3.4
  fluttertoast: ^8.0.9
  share_plus: ^4.1.0
  flutter_contacts: ^1.1.5
  assets_audio_player: ^3.0.5
  url_launcher: ^6.1.5
  qrscan: ^0.3.3
  permission_handler: ^10.0.0
  google_mobile_ads: ^2.0.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/onboarding/group.png
    - assets/images/onboarding/member.png
    - assets/images/onboarding/reward.png
    - assets/images/banner.jpg
    - assets/images/arisan-blue.png
    - assets/images/arisan-white.png
    - assets/images/icons/google.png
    - assets/images/icons/man.png
    - assets/images/icons/woman.png
    - assets/images/icons/reward.png
    - assets/images/icons/shuffle.png
    - assets/images/icons/group.png
    - assets/images/icons/trophy.png
    - assets/images/icons/trophy-circle.png
    - assets/images/icons/trophy-circle-2.png
    - assets/images/icons/trophy-circle-3.png
    - assets/images/icons/empty.png
    - assets/images/icons/whatsapp.png
    - assets/images/world-group.png
    - assets/audios/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
